version: '3.7'

services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.local
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8080:8080'
